### ISSUE TITLE
Remove mandatory dependency on Simple Storage Network

### ISSUE THREAD

**Issue by iwolfking** [BONNePlayground/VaultHuntersJewelSorting#5]
Hello, due to some changes to my custom Vault Hunters pack (Wold's Vaults), Simple Storage Network was removed from the pack.

Thus, the Vault Hunters Jewel Sorting mod is no longer compatible, since in the mods.toml file, storagenetwork is listed as a mandatory dependency. It looks like the mixins will not apply when the mod is not present, so it would be nice if the mod was not listed as a mandatory dependency (and really any mod where it will load fine without the mod being there).

The mod works fine when manually editing the mods.toml file to remove the storagenetwork dependency.

**Comment by BONNe** [comment]
Implemented in version 2.5.0
